name: u24_element_tag_to_release
on:
  push:
    tags:
      - '*.*.*'
      - 'test*.*.*'
jobs:
  call_context_check:
    uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
  call_mkdocs_release:
    uses: yambottle/datajoint.github/.github/workflows/mkdocs_release.yaml@main
    permissions: write-all

